name: blog
dependencies:
- openssl=1.0.2d=0
- pip=7.1.2=py27_0
- python=2.7.11=0
- readline=6.2=2
- setuptools=19.1.1=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - alabaster==0.7.7
  - astroid==1.3.6
  - babel==2.1.1
  - blinker==1.4
  - cpplint==0.0.6
  - cssselect==0.9.1
  - cycler==0.9.0
  - docutils==0.12
  - ecdsa==0.13
  - fabric==1.10.2
  - feedgenerator==1.7
  - funcsigs==0.4
  - ghp-import==0.4.1
  - jinja2==2.8
  - logilab-common==1.0.2
  - lxml==3.5.0
  - markdown==2.6.5
  - markupsafe==0.23
  - matplotlib==1.5.1
  - mercurial==3.8.1
  - mock==1.3.0
  - nose==1.3.7
  - numpy==1.11.0
  - paramiko==1.16.0
  - pbr==1.8.1
  - pelican==3.6.3
  - protobuf==2.6.1
  - pycrypto==2.6.1
  - pygments==2.0.2
  - pygobject==3.20.1
  - pylint==1.4.4
  - pyparsing==2.0.6
  - pyquery==1.2.9
  - python-dateutil==2.4.2
  - pytz==2015.7
  - six==1.10.0
  - snowballstemmer==1.2.0
  - sphinx==1.3.3
  - sphinx-rtd-theme==0.1.9
  - stevedore==1.6.0
  - tinkerer==1.5
  - unidecode==0.4.18
  - virtualenv==13.1.2
  - virtualenv-clone==0.2.6

